<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\Auth\Queries\" />
      <Folder Include="Features\Categories\Services\" />
      <Folder Include="Features\Transactions\Queries\GetAllTransactions\" />
      <Folder Include="Features\UserBalances\Commands\" />
      <Folder Include="Features\Users\Queries\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyBudgetManager.Domain\MyBudgetManager.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="FluentValidation" Version="12.0.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
      <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.9" />
    </ItemGroup>

</Project>
